# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='desc',
            field=models.CharField(max_length=20, verbose_name='\u5907\u6ce8'),
        ),
    ]
